### ISSUE TITLE
Table rendered as text in "Creating SLA Domains"

### ISSUE THREAD

**Issue by kamjain** [rubrikinc/api-documentation#5]
The following issue pertains to "Creating SLA Domains" sub-section at https://rubrikinc.github.io/api-doc-v2-5.2/#section/SLA-Domains/Creating-SLA-Domains

**What happened**: The table that describes the required attributes for each time unit in `frequency` is rendered as raw text.

**What you expected to happen**: It should have been a well-formatted table like the one above it.

**How to reproduce it (as minimally and precisely as possible)**: Go to https://rubrikinc.github.io/api-doc-v2-5.2/#section/SLA-Domains/Creating-SLA-Domains, scroll down until you reach just under the first table. 

**Anything else we need to know?**:

**Environment**: Firefox 79.0
- SDK version:
- OS Windows 10
- Others:

**Comment by jaapbrasser** [comment]
Hey @kamjain,

I fixed this issue, the updated documentation is live here: [Rubrik REST API v2 - SLA Domains](https://rubrikinc.github.io/api-doc-v2-5.2/#section/SLA-Domains)

Thanks for reporting these two issues in the documentation!
