### ISSUE TITLE
Typo in example for "Retrieving SLA Domains"

### ISSUE THREAD

**Issue by kamjain** [rubrikinc/api-documentation#6]
**What happened**:  In the section describing the endpoint to get details on a specific SLA Domain (with a given id), the example provided is the same as the endpoint.
<img width="954" alt="Retrieving a specific SLA Domain" src="https://user-images.githubusercontent.com/60113063/90682365-b2cc1380-e219-11ea-9c28-10a717865101.png">

**What you expected to happen**: It should look like this - 
For more details about an SLA domain, send a GET request to the `/sla_domain/{id}` endpoint and provide the ID of the SLA domain, for example: `/sla_domain/$bronze_sla_id`

**How to reproduce it (as minimally and precisely as possible)**: Go to https://rubrikinc.github.io/api-doc-v2-5.2/#section/SLA-Domains/Retrieving-SLA-Domains. The line that needs to be fixed is right under the code block that describes the `ListResponse` returned as a result of the GET request sent to `/sla_domain`

**Anything else we need to know?**: Attached a screenshot.

**Environment**: Firefox 79.0
- SDK version:
- OS Windows 10
- Others:

**Comment by jaapbrasser** [comment]
Hey @kamjain,

Sorry for the slow response I didn't have notifications setup on this repository. I fixed this issue, the updated documentation is live here: [https://rubrikinc.github.io/api-doc-v2-5.2/#section/SLA-Domains](Rubrik REST API v2 - SLA Domains)
