### ISSUE TITLE
Please add the API v3 documentation this page

### ISSUE THREAD

**Issue by IamTHEvilONE** [rubrikinc/api-documentation#8]
**What would you like to be added**:
5.2.x added a v3 API for SLA Domains (patch)

**Why is this needed**:
it's absent from the online documentation.

**Comment by jaapbrasser** [comment]
Thanks for reporting this @IamTHEvilONE, I will work to get this resolved asap.

**Comment by jaapbrasser** [comment]
Hello @IamTHEvilONE,

Docs have been updated, both 5.2 & 5.3 v3 docs have been added!

![image](https://user-images.githubusercontent.com/12744735/106531619-e14f5980-64ee-11eb-8433-0c332b01e4a3.png)


Let me know if there's anything else we can do!
